### PR TITLE
Remove test case with non-ASCII characters b/c it is 2020 and we still cannot have nice things

### LINKED ISSUE #27: Install in Windows failed
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Install fails when trying to create a new/clean environment with OpenQuake:

<details>

```
(base) D:\src\>conda create -y -n testoq -c conda-forge --channel-priority openquake.engine
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\miniconda\envs\testoq

  added / updated specs:
    - openquake.engine


The following NEW packages will be INSTALLED:

  asgiref            conda-forge/noarch::asgiref-3.3.1-pyhd8ed1ab_0
  brotlipy           conda-forge/win-64::brotlipy-0.7.0-py38hab1e662_1001
  ca-certificates    conda-forge/win-64::ca-certificates-2020.12.5-h5b45459_0
  cached-property    conda-forge/noarch::cached-property-1.5.1-py_0
  certifi            conda-forge/win-64::certifi-2020.12.5-py38haa244fe_0
  cffi               conda-forge/win-64::cffi-1.14.4-py38hd8c33c5_1
  chardet            conda-forge/win-64::chardet-3.0.4-py38h9bdc248_1008
  cryptography       conda-forge/win-64::cryptography-3.3.1-py38hd8c33c5_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  django             conda-forge/noarch::django-3.1.4-pyhd8ed1ab_0
  docutils           conda-forge/win-64::docutils-0.16-py38h9bdc248_2
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_0
  geos               conda-forge/win-64::geos-3.8.1-he025d50_0
  h5py               conda-forge/win-64::h5py-3.1.0-nompi_py38h022eade_100
  hdf5               conda-forge/win-64::hdf5-1.10.6-nompi_h5268f04_1112
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  intel-openmp       conda-forge/win-64::intel-openmp-2020.3-h57928b3_311
  jpeg               conda-forge/win-64::jpeg-9d-h8ffe710_0
  kiwisolver         conda-forge/win-64::kiwisolver-1.3.1-py38hbd9d945_0
  krb5               conda-forge/win-64::krb5-1.17.2-hbae68bd_0
  libblas            conda-forge/win-64::libblas-3.8.0-21_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-21_mkl
  libcurl            conda-forge/win-64::libcurl-7.71.1-h4b64cdc_8
  liblapack          conda-forge/win-64::liblapack-3.8.0-21_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  libsodium          conda-forge/win-64::libsodium-1.0.17-h2fa13f4_0
  libssh2            conda-forge/win-64::libssh2-1.9.0-hb06d900_5
  libtiff            conda-forge/win-64::libtiff-4.1.0-hc10be44_6
  lz4-c              conda-forge/win-64::lz4-c-1.9.2-h62dcd97_2
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.3.3-py38h34ddff4_0
  mkl                conda-forge/win-64::mkl-2020.4-hb70f87d_311
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  numpy              conda-forge/win-64::numpy-1.19.4-py38h0cc643e_1
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openquake.engine   conda-forge/noarch::openquake.engine-3.8.1-py_1
  openssl            conda-forge/win-64::openssl-1.1.1h-he774522_0
  pandas             conda-forge/win-64::pandas-1.1.5-py38h4c96930_0
  pillow             conda-forge/win-64::pillow-8.0.1-py38hd8d9125_0
  pip                conda-forge/noarch::pip-20.3.1-pyhd8ed1ab_0
  psutil             conda-forge/win-64::psutil-5.7.3-py38hab1e662_0
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pyreadline         conda-forge/win-64::pyreadline-2.1-py38h32f6830_1002
  pyshp              conda-forge/noarch::pyshp-2.1.2-pyh9f0ad1d_0
  pysocks            conda-forge/win-64::pysocks-1.7.1-py38h9bdc248_2
  python             conda-forge/win-64::python-3.8.6-h7840368_1_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/win-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.4-pyhd8ed1ab_0
  pyyaml             conda-forge/win-64::pyyaml-5.3.1-py38hab1e662_1
  pyzmq              conda-forge/win-64::pyzmq-18.1.1-py38h16f9016_0
  requests           conda-forge/noarch::requests-2.25.0-pyhd3deb0d_0
  scipy              conda-forge/win-64::scipy-1.5.3-py38h5f893b4_0
  setuptools         conda-forge/win-64::setuptools-49.6.0-py38h9bdc248_2
  shapely            conda-forge/win-64::shapely-1.7.1-py38hc96c142_1
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/win-64::sqlite-3.34.0-h8ffe710_0
  sqlparse           conda-forge/noarch::sqlparse-0.4.1-pyh9f0ad1d_0
  tk                 conda-forge/win-64::tk-8.6.10-he774522_1
  toml               conda-forge/noarch::toml-0.10.2-pyhd8ed1ab_0
  tornado            conda-forge/win-64::tornado-6.1-py38h294d835_0
  urllib3            conda-forge/noarch::urllib3-1.25.11-py_0
  vc                 conda-forge/win-64::vc-14.1-h869be7e_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.16.27012-h30e32a0_2
  wheel              conda-forge/noarch::wheel-0.36.1-pyhd3deb0d_0
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py38h32f6830_1
  wincertstore       conda-forge/win-64::wincertstore-0.2-py38h32f6830_1005
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  yaml               conda-forge/win-64::yaml-0.2.5-he774522_0
  zeromq             conda-forge/win-64::zeromq-4.3.2-ha925a31_3
  zlib               conda-forge/win-64::zlib-1.2.11-h62dcd97_1010
  zstd               conda-forge/win-64::zstd-1.4.5-h1f3a1b7_2


Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for openquake.engine located at D:\miniconda\pkgs\openquake.engine-3.8.1-py_1
appears to be corrupted. The path 'site-packages/openquake/qa_tests_data/classical_risk/case_5/èxposure_model.xml'
specified in the package manifest cannot be found.
```

</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at D:\miniconda:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2020.10.14                    0
certifi                   2020.6.20          pyhd3eb1b0_3
cffi                      1.14.3           py38hcd4344a_2
chardet                   3.0.4           py38haa95532_1003
conda                     4.9.2            py38haa95532_0
conda-package-handling    1.7.2            py38h76e460a_0
console_shortcut          0.1.1                         4
cryptography              3.2.1            py38hcd4344a_1
idna                      2.10                       py_0
menuinst                  1.4.16           py38he774522_1
openssl                   1.1.1h               he774522_0
pip                       20.2.4           py38haa95532_0
powershell_shortcut       0.0.1                         3
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.20                       py_2
pyopenssl                 19.1.0             pyhd3eb1b0_1
pysocks                   1.7.1            py38haa95532_0
python                    3.8.5                h5fd99cc_1
pywin32                   227              py38he774522_1
requests                  2.24.0                     py_0
ruamel_yaml               0.15.87          py38he774522_1
setuptools                50.3.1           py38haa95532_1
six                       1.15.0           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
tqdm                      4.51.0             pyhd3eb1b0_0
urllib3                   1.25.11                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
yaml                      0.2.5                he774522_0
zlib                      1.2.11               h62dcd97_4
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : D:\miniconda
            shell level : 1
       user config file : C:\Users\emtmo\.condarc
 populated config files : C:\Users\emtmo\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\miniconda\pkgs
                          C:\Users\emtmo\.conda\pkgs
                          C:\Users\emtmo\AppData\Local\conda\conda\pkgs
       envs directories : D:\miniconda\envs
                          C:\Users\emtmo\.conda\envs
                          C:\Users\emtmo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #27

### CODE REVIEW

**Comment by ocefpaf** [comment]
@emthompson-usgs I can reproduce the error you are experimenting. Working on a fix now...

**Comment by emthompson-usgs** [comment]
Since the error message was that the file is expected because it is in the manifest, but not cannot be found, I was wondering if you think it would make sense to try to remove the two lines in the manifest that include the testing data:
```
# QA tests data
recursive-include openquake/qa_tests_data *.* README
recursive-exclude openquake/qa_tests_data *.pyc
```

**Comment by ocefpaf** [comment]
> Since the error message was that the file is expected because it is in the manifest, but not cannot be found

I'm not sure that is the failure here b/c it only happens on Windows, while we are removing that file from all builds.

> I was wondering if you think it would make sense to try to remove the two lines in the manifest that include the testing data:
> 
> ```
> # QA tests data
> recursive-include openquake/qa_tests_data *.* README
> recursive-exclude openquake/qa_tests_data *.pyc
> ```

We can try but there are already a few workarounds in this packages. We are breaking the dependency pinning in the metadata, removing files in the MANIFEST, etc. It would be better to solve those issues upstream and as for a new release.

**Comment by emthompson-usgs** [comment]
Thanks for looking at this and trying to fix it @ocefpaf. I agree that the solution would be better handled upstream, but we aren't part of the OpenQuake development team and they don't use conda. Ideally, they would maintain the conda package. We only do it because we use conda to manage our dependencies, and make heavy us of OpenQuake. I'll close out these PRs and the associated issue and try to coordinate with the OpenQuake to find a solution.

**Comment by ocefpaf** [comment]
I'll get my hands on a Windows machine later today and I'll give it a try. So far no success in #30 but I still have a few tricks I want to try...

**Comment by ocefpaf** [comment]
@emthompson-usgs this should work on Windows. I just tested it locally but for reason I cannot make it work on Azure (more my lack of understanding of Windows than anything else.)

BTW, while trying to fix this upstream would be nice, something like splitting the test cases from the main package to make it easier to package and ship, this is really a bug in conda. It should handle those special characters on Windows.

**Comment by emthompson-usgs** [comment]
Thanks so much for your efforts on this!

**Comment by ocefpaf** [comment]
Let me know if that works for you.

**Comment by emthompson-usgs** [comment]
@ocefpaf I've installed it on our Windows system and ran some tests. It is indeed working! This was a big step towards being able to support Windows systems for our group. If you know of any example conda packages that use cython and build on Windows that I can use as an example to follow, please let me know.

**Comment by ocefpaf** [comment]
> If you know of any example conda packages that use cython and build on Windows that I can use as an example to follow, please let me know.

Are you adding a new package? Is it on PyPI? If so you can try [grayskull to generate the recipe](https://github.com/conda-incubator/grayskull#usage) and it should do the right thing if the package has the proper metadata. I recommend to send a PR [to staged-recipes](https://github.com/conda-forge/staged-recipes) and asking for help there for the details of the recipe.

**Comment by emthompson-usgs** [comment]
It isn't new or on PyPi. It is just a [package](https://github.com/conda-forge/gmprocess-feedstock) that uses cython. It works fine in linux/OSX, and I am in the process of trying to get it to support Windows. Given my lack of familiarity with Windows I was thinking that having an example conda package that deals with the C compiler for Windows builds would be helpful.

**Comment by ocefpaf** [comment]
Let's follow up on that in the feedstock. It looks like there is no skip for Windows but a re-render may be missing.

**Pull request merged**
